#! /bin/sh

sxhkd &

bspc monitor -d    

bspc config border_width                0
bspc config window_gap                  37

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config normal_border_color           "#2b303b"
bspc config focused_border_color          "#3c414c"

bspc config top_padding                   50
bspc config bottom_padding                10
bspc config single_monocle                true
bspc config pointer_follows_monitor       true
bspc config focus_follows_pointer         true
bspc config click_to_focus                true
bspc config presel_feedback_color         "$COLOR_HIGHLIGHT"

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a plasmashell manage=off 
bspc rule -a Plasma manage=off
bspc rule -a plasma-desktop manage=off
bspc rule -a python3 state=floating
bspc rule -a yakuake state=floating

compton --config "$HOME/.config/compton.conf" -b
