#!/bin/bash

# --NIGHT-MODE

HOME='/home/rene'
NITRO=$HOME'/.config/nitrogen/bg-saved.cfg'
GTK2=$HOME'/.gtkrc-2.0'
GTK3=$HOME'/.config/gtk-3.0/settings.ini'
ROFI=$HOME'/.config/rofi/config'
I3CONF=$HOME'/.config/i3/config'

# WALLPAPER
nitrogen --set-zoom-fill $HOME/.wallpapers/flat_planet.png
sed -i 's^file=.*^file=/home/rene/\.wallpapers/flat_planet.png^' $NITRO

# GTK2 THEME
sed -i 's^gtk-theme-name=.*^gtk-theme-name="Breeze-Dark"^' $GTK2

# GTK3 THEME
sed -i 's^gtk-theme-name=.*^gtk-theme-name=Breeze-Dark^' $GTK3

# XRESOURCES
sed -i 's^rofi.color-window.*^rofi.color-window: #242a34, #242a34, #242a34^' $ROFI
sed -i 's^rofi.color-normal.*^rofi.color-normal: #242a34, #b7bdca, #242a34, #242a34, #bf616a, #3377cc^' $ROFI

# i3 CONFIG
sed -i 's^set \$border.*^set \$border     \#2b303bCC^' $I3CONF
sed -i 's^set \$background.*^set \$background \#2b303bCC^' $I3CONF
sed -i 's^set \$text.*^set \$text       \#a7adbaFF^' $I3CONF
sed -i 's^set \$active.*^set \$active     \#bf616aFF^' $I3CONF
sed -i 's^set \$inactive.*^set \$inactive   \#a7adbaFF^' $I3CONF
sed -i 's^client.focused.*^client.focused          \$background \$background \$text       $background $background^' $I3CONF
sed -i 's^client.focused_inactive.*^client.focused_inactive \$inactive   \$inactive   \$background $background $background^' $I3CONF
sed -i 's^focused_workspace.*^focused_workspace  \$active  \$active       \$background^' $I3CONF
sed -i 's^compton -b.*^compton -b --config ~/.config/compton.night.conf^' $I3CONF
i3-msg restart
